name: Test and Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

#      - name: Rename ChromeDriver for Linux
#        run: mv src/main/resources/chromedriver src/main/resources/chromedriver.exe

      - name: Build and test with Maven
        run: mvn clean test -Dexclude=**/ButtonTest.java,**/DownloadUploadTest.java
#          if [[ "$RUNNER_OS" == "Linux" ]]; then
#            echo "Running tests with Linux driver"
#            mvn clean test -Dwebdriver.chrome.driver=$(pwd)/src/main/resources/chromedriver
#          elif [[ "$RUNNER_OS" == "Windows" ]]; then
#            echo "Running tests with Windows driver"
#            mvn clean test -Dwebdriver.chrome.driver=$(pwd)/src/main/resources/chromedriver.exe
#          else
#            echo "Unsupported OS"
#            exit 1
#          fi

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: target/
            keep_files: true
            destination_dir: reports

      - name: Notify completion
        run: echo "Build and tests completed!"